name: 'build'

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build bokkdown site and PDF
      run: |
        docker build -t gh-facts - < Rmd/Dockerfile
        docker run --rm -v $(pwd):/src gh-facts

    - uses: actions/upload-artifact@v2
      with:
        name: github-facts
        path: _book

    - name: Publish site to gh-pages
      if: github.event_name != 'pull_request'
      run: |
        cp -r _book public
        cd public
        touch .nojekyll
        git init
        cp ../.git/config ./.git/config
        git checkout --orphan gh-pages
        git add .
        git config --local user.email "push@gha"
        git config --local user.name "GHA"
        git commit -a -m "update ${{ github.sha }}"
        git push -u origin +gh-pages
